import { Timestamp } from 'firebase/firestore';

export type channelsList = {
    id: string;
    displayName: string;
    icon: string;
    message: string;
    timestamp: Timestamp; // Unix time
    unread: number;
};
export const useDummy = ()=>{
    // dummyData.ts
    const now = Date.now();
    const dummyChannelsList: channelsList[] = [
    {
      id: "user1",
      displayName: "佐藤 太郎",
      icon: "https://i.pravatar.cc/150?img=1",
      message: "こんにちは！元気ですか？",
      // timestamp: Math.floor(Date.now() / 1000) - 30,
      timestamp:Timestamp.fromMillis(now - 30 * 1000),
      unread: 2,
    },
    {
      id: "user2",
      displayName: "鈴木 花子",
      icon: "https://i.pravatar.cc/150?img=2",
      message: "that is a great idea! what dase is kesike jf",
      // timestamp: Math.floor(Date.now() / 1000) - 120,
      timestamp: Timestamp.fromMillis(now - 120 * 1000),
      unread: 0,
    },
    {
      id: "user3",
      displayName: "田中 一郎",
      icon: "https://i.pravatar.cc/150?img=3",
      message: "ありがとう！助かったよ！",
      // timestamp: Math.floor(Date.now() / 1000) - 600,
      timestamp: Timestamp.fromMillis(now - 600 * 1000),
      unread: 5,
    },
    {
      id: "user4",
      displayName: "山田 美咲",
      icon: "https://i.pravatar.cc/150?img=4",
      message: "資料を確認しました。",
      // timestamp: Math.floor(Date.now() / 1000) - 1800,
      timestamp: Timestamp.fromMillis(now - 1000 * 1000),
      unread: 1,
    },
    {
      id: "user5",
      displayName: "高橋 健",
      icon: "https://i.pravatar.cc/150?img=5",
      message: "また連絡するね！",
      // timestamp: Math.floor(Date.now() / 1000) - 7200,
      timestamp:Timestamp.fromMillis(now - 7200 * 1000),
      unread: 0,
    },
    {
      id: "user6",
      displayName: "中村 涼",
      icon: "https://i.pravatar.cc/150?img=6",
      message: "今週の予定は？",
      // timestamp: Math.floor(Date.now() / 1000) - 15000,
      timestamp: Timestamp.fromMillis(now - 15000 * 1000),
      unread: 3,
    },
    {
      id: "user7",
      displayName: "小林 彩",
      icon: "https://i.pravatar.cc/150?img=7",
      message: "もうすぐ着くよ。",
      // timestamp: Math.floor(Date.now() / 1000) - 86400,
      timestamp: Timestamp.fromMillis(now - 86400 * 1000),
      unread: 0,
    },
    {
      id: "user8",
      displayName: "加藤 翼",
      icon: "https://i.pravatar.cc/150?img=8",
      message: "来週打ち合わせしよう。",
      // timestamp: Math.floor(Date.now() / 1000) - 172800,
      timestamp: Timestamp.fromMillis(now - 172800 * 1000),
      unread: 7,
    },
    {
      id: "user9",
      displayName: "井上 結衣",
      icon: "https://i.pravatar.cc/150?img=9",
      message: "旅行楽しんできて！",
      // timestamp: Math.floor(Date.now() / 1000) - 259200,
      timestamp: Timestamp.fromMillis(now - 259200 * 1000),
      unread: 0,
    },
    {
      id: "user10",
      displayName: "渡辺 海斗",
      icon: "https://i.pravatar.cc/150?img=10",
      message: "写真送ってくれる？",
      // timestamp: Math.floor(Date.now() / 1000) - 604800,
      timestamp: Timestamp.fromMillis(now - 604800 * 1000),
      unread: 4,
    },
    {
        id: "user21",
        displayName: "佐藤 花子",
        icon: "/icons/user21.png",
        message: "了解しました！",
        timestamp: Timestamp.fromMillis(now - 604800 * 1000),
        unread: 0,
      },
      {
        id: "user22",
        displayName: "田中 太郎",
        icon: "/icons/user22.png",
        message: "明日確認します。",
        timestamp: Timestamp.fromMillis(now - 604800 * 1000),
        unread: 1,
      },
      {
        id: "user23",
        displayName: "山本 一郎",
        icon: "/icons/user23.png",
        message: "資料ありがとうございます。",
        timestamp: Timestamp.fromMillis(now - 604800 * 1000),
        unread: 1,
      },
      {
        id: "user24",
        displayName: "鈴木 真由",
        icon: "/icons/user24.png",
        message: "あとで打ち合わせしましょう。",
        timestamp: Timestamp.fromMillis(now - 604800 * 1000),
        unread: 0,
      },
      {
        id: "user25",
        displayName: "高橋 健太",
        icon: "/icons/user25.png",
        message: "送信しました！",
        timestamp: Timestamp.fromMillis(now - 604800 * 1000),
        unread: 1,
      },
      {
        id: "user26",
        displayName: "中村 美咲",
        icon: "/icons/user26.png",
        message: "よろしくお願いします！",
        timestamp: Timestamp.fromMillis(now - 604800 * 1000),
        unread: 1,
      },
      {
        id: "user27",
        displayName: "加藤 大輔",
        icon: "/icons/user27.png",
        message: "急ぎでお願いします。",
        timestamp: Timestamp.fromMillis(now - 604800 * 1000),
        unread: 0,
      },
      {
        id: "user28",
        displayName: "小林 裕子",
        icon: "/icons/user28.png",
        message: "今日の進捗です。",
        timestamp: Timestamp.fromMillis(now - 604800 * 1000),
        unread: 1,
      },
      {
        id: "user29",
        displayName: "斎藤 慎一",
        icon: "/icons/user29.png",
        message: "会議はキャンセルになりました。",
        timestamp: Timestamp.fromMillis(now - 604800 * 1000),
        unread: 0,
      },
      {
        id: "user30",
        displayName: "渡辺 美和",
        icon: "/icons/user30.png",
        message: "承知しました。",
        timestamp: Timestamp.fromMillis(now - 604800 * 1000),
        unread: 1,
      },
      {
        id: "user31",
        displayName: "井上 拓海",
        icon: "/icons/user31.png",
        message: "対応完了しました。",
        timestamp: Timestamp.fromMillis(now - 604800 * 1000),
        unread: 1,
      },
      {
        id: "user32",
        displayName: "松本 優",
        icon: "/icons/user32.png",
        message: "進捗を共有します。",
        timestamp: Timestamp.fromMillis(now - 604800 * 1000),
        unread: 0,
      },
      {
        id: "user33",
        displayName: "石川 彩",
        icon: "/icons/user33.png",
        message: "提出しました。",
        timestamp: Timestamp.fromMillis(now - 604800 * 1000),
        unread: 0,
      },
      {
        id: "user34",
        displayName: "木村 直人",
        icon: "/icons/user34.png",
        message: "今晩打ち合わせできますか？",
        timestamp: Timestamp.fromMillis(now - 604800 * 1000),
        unread: 1,
      },
      {
        id: "user35",
        displayName: "林 さくら",
        icon: "/icons/user35.png",
        message: "よろしくお願いします。",
        timestamp: Timestamp.fromMillis(now - 604800 * 1000),
        unread: 1,
      },
      {
        id: "user36",
        displayName: "清水 拓也",
        icon: "/icons/user36.png",
        message: "すぐ対応します。",
        timestamp: Timestamp.fromMillis(now - 604800 * 1000),
        unread: 0,
      },
      {
        id: "user37",
        displayName: "山田 理沙",
        icon: "/icons/user37.png",
        message: "ありがとうございます！",
        timestamp: Timestamp.fromMillis(now - 604800 * 1000),
        unread: 1,
      },
      {
        id: "user38",
        displayName: "藤田 翔",
        icon: "/icons/user38.png",
        message: "本日提出します。",
        timestamp: Timestamp.fromMillis(now - 604800 * 1000),
        unread: 0,
      },
      {
        id: "user39",
        displayName: "三浦 結衣",
        icon: "/icons/user39.png",
        message: "ご確認ください。",
        timestamp: Timestamp.fromMillis(now - 604800 * 1000),
        unread: 1,
      },
      {
        id: "user40",
        displayName: "岡田 悠真",
        icon: "/icons/user40.png",
        message: "先ほどの件ですが…",
        timestamp: Timestamp.fromMillis(now - 604800 * 1000),
        unread: 1,
      },
  ];
  return{dummyChannelsList}
}